name = "TerminalPager"
uuid = "0c614874-6106-40ed-a7c2-2f1cd0bff883"
license = "MIT"
desc = "Pure Julia implementation of a terminal pager"
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "0.6.10"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
StringManipulation = "892a3eda-7b42-436c-8928-eab12a02cf0e"

[weakdeps]
About = "69d22d85-9f48-4c46-bbbe-7ad8341ff72a"

[extensions]
TerminalPagerAboutExt = "About"

[compat]
About = "1"
Crayons = "4.0"
Markdown = "1.10"
PrecompileTools = "1"
Preferences = "1"
StringManipulation = "0.3.2, 0.4"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
